#!/bin/bash

#PBS -N mol_din
#PBS -l walltime=00:35:00
#PBS -l nodes=1:ppn=20

module load openmpi/1.8.3/gnu/4.9.2

# -q reserved3

cd $PBS_O_WORKDIR

if [ -f simple_output.dat ]
then
    rm simple_output.dat
fi

mpirun -np 10 src/simplemd.x in0 in1 in2 in3 in4 in5 in6 in7 in8 in9
